### ISSUE TITLE
w1temp and wiringPi

### ISSUE THREAD

**Issue by pieman64** [kolarcz/node-w1temp#1]
@kolarcz can w1temp co-exist with wiringPi or does wiringPi need to be removed / disabled?

The pin references in your example, what are they:
1) BCM references
2) wiringPi references
3) Physical pin references
4) Official GPIO references
5) Some other references

At the moment when I run yor example with:

`sudo node example.js`

I have disabled the power pin in the js and I haven't done the modprobe or config.txt edit as I thought it could all be done with sudo.

I will keep trying.

**Comment by pieman64** [comment]
```
Temp changed: 22.625 °C
Temp changed: 22.687 °C
Temp changed: 22.625 °C
Temp changed: 22.687 °C
Temp changed: 22.625 °C
Temp changed: 22.687 °C
Temp changed: 22.625 °C
Temp changed: 22.687 °C
Temp changed: 22.625 °C
```
All working fine with the GPIO references being from the BCM table.

**Comment by kolarcz** [comment]
Thanks, maybe I should write which reference I am using.

**Comment by TyroneBurns** [comment]
can you help? I can not get temp display on the blynk app? 

I have used:
cat /sys/bus/w1/devices/28-041692d33eff/w1_slave | sed -n 's/^.*\(t=[^ ]*\).*/\1/p' | sed 's/t=//' | awk '{x=$1}END{print(x/1000)}'

which shows the current temp so I know the sensor is good, and Ive also installed w1temp library. 

Im very new to this but understand basic python and java coding.
